name: social_media
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  # Core Packages
  dio: ^5.4.0
  http: ^1.4.0
  intl: ^0.19.0
  linkify: ^5.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  camera: ^0.11.1
  path_provider: ^2.1.3
  uuid: ^4.0.0
  timeago: ^3.2.2
  google_fonts: ^6.2.1
  provider: ^6.1.2

  # Firebase Services - Updated versions
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^17.0.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.10

  # UI & Animations
  flutter_svg: ^2.1.0
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  feather_icons: ^1.2.0
  line_icons: ^2.0.3
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0

  # Media & Video Support
  video_player: ^2.8.2
  chewie: ^1.7.5
  better_player: ^0.0.83    # Added better_player for enhanced video support
  
  # Audio Support
  audioplayers: ^5.2.1
  
  # Web Support
  video_player_web: ^2.3.5

  # Caching & Network
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.0
  like_button: ^2.0.5
  visibility_detector: ^0.4.0+2

  # Storage
  sqflite: ^2.3.3

  # Device Info
  device_info_plus: ^10.0.0
  http_parser: ^4.1.2
  path: ^1.9.1
  carousel_slider: ^5.0.0
  flutter_linkify: ^6.0.0
  package_info_plus: ^8.3.0
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo.png
  
dependency_overrides:
  web: ^0.5.1
  
